### ISSUE TITLE
How to initialize cloudboost with my own server in android App?

### ISSUE THREAD

**Issue by pawarn** [CloudBoost/JavaSDK#9]
I am not able to initialize cloudboost with my own server.

I user  CloudApp.init(appId, appKey)

also tried  CloudApp.serverUrl = serverUrl;

**Comment by nawazdhandala** [comment]
Try CloudApp.init(sererUrl, appId, appKey)

**Comment by nawazdhandala** [comment]
P.S: We ONLY support JavaScript. We dont support Android.

**Comment by pawarn** [comment]
Thanks for the instant reply.
I have already tried CloudApp.init(sererUrl, appId, appKey) but there is no such method with 3 parameters in library  **compile 'io.cloudboost:JavaSDK:1.0.3'**

Is there any other way to use cloudboost with android?

**Comment by nawazdhandala** [comment]
Yes. We don’t support that SDK.

**Comment by pawarn** [comment]
Thanks, @nawazdhandala for the great library.

We would expect support for Android in future.
